[package]
name = "v-ayylmao"
version = "0.1.0"
edition = "2021"

[dependencies]
libloading = "0.7.3"
bitflags = "1.3.2"
once_cell = "1.13.1"
raw-window-handle = "0.5.0"
log = "0.4.17"
bytemuck = { version = "1.12.1", features = ["derive", "min_const_generics"] }

[dev-dependencies]
winit = "0.27.2"
env_logger = "0.9.0"
jfifdump = "0.3.1"
softbuffer = "0.1.1"
jpeg-decoder = "0.2.6"
anyhow = "1.0.68"
byteorder = "1.4.3"
